#!/usr/bin/env python3

from utils import (
    timestamp_file,
    get_audio_input_device,
    notify,
    take_screenshot,
)
import subprocess
import os
from typing import Tuple
from enum import Enum


class RecordingOption(Enum):
    SCREENSHOT_REGION = "󰩭 Region"
    SCREEN_AND_MIC = "󰍹 󰍬"
    SCREEN_AND_SYS = "󰍹 󰕾"
    SCREEN_ONLY = "󰍹 󰖁"
    AUDIO_ONLY = "󰍬"
    SCREENSHOT = "󰄀"


STOP_RECORDING = "󰓛"


VIDEO_DIR = os.path.expanduser("~/Videos")
CONFIG_DIR = os.path.expanduser("~/.config/rofi")


def get_cmd_for(process_name):
    result = subprocess.run(
        ["pgrep", "-f", process_name], capture_output=True, text=True
    )

    if result.returncode != 0:
        return None

    pid = result.stdout.strip().split("\n")[0]
    cmd = ["ps", "-p", pid, "-o", "args", "--no-headers"]
    res = subprocess.run(cmd, capture_output=True, text=True)

    return res.stdout.strip() if res.returncode == 0 else None


def take_region_screenshot():
    IMAGE_DIR = os.path.expanduser("~/Pictures/Screenshots")
    os.makedirs(IMAGE_DIR, exist_ok=True)
    out = timestamp_file("screenshot", "png", IMAGE_DIR)
    try:
        region = subprocess.run(
            ["slurp"], capture_output=True, text=True, check=True
        ).stdout.strip()
        subprocess.Popen(["grim", "-g", region, out])
        notify("Screenshot Taken", out)
    except subprocess.CalledProcessError:
        pass  # user cancelled slurp


def get_recording_info():
    wf = get_cmd_for("wf-recorder")
    mic_name = get_audio_input_device()

    if wf:
        if "--audio=default" in wf:
            audio = f"microphone ({mic_name})"
        elif "--audio" in wf:
            audio = "system audio"
        else:
            audio = "silent"

        parts = wf.split()
        outfile = parts[parts.index("-f") + 1] if "-f" in parts else "unknown"

        return ("screen", audio, outfile)

    ff = get_cmd_for("ffmpeg")
    if ff:
        rec_type = "audio-only"

        audio = f"microphone ({mic_name})"
        outfile = ff.split()[-1]
        return (rec_type, audio, outfile)


def start_screen_mic():
    mic = get_audio_input_device()
    out = timestamp_file("recording", "mp4", VIDEO_DIR)
    subprocess.Popen(
        ["wf-recorder", "--audio=default", "-f", out],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    notify("Recording Started", f"Screen + microphone ({mic})\n{out}")


def start_screen_system_audio():
    out = timestamp_file("recording", "mp4", VIDEO_DIR)
    subprocess.Popen(
        ["wf-recorder", "--audio", "-f", out],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    notify("Recording Started", f"Screen + system audio\n{out}")


def start_audio_only():
    mic = get_audio_input_device()
    out = timestamp_file("audio", "mp3", VIDEO_DIR)
    subprocess.Popen(
        ["ffmpeg", "-f", "pulse", "-i", "default", "-c:a", "mp3", out],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    notify("Audio Recording", f"Mic: {mic}\n{out}")


def start_screen_silent():
    out = timestamp_file("recording", "mp4", VIDEO_DIR)
    subprocess.Popen(
        ["wf-recorder", "-f", out],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    notify("Recording Started", f"Screen only\n{out}")


def stop_recording():
    subprocess.run(["pkill", "-f", "wf-recorder"])
    subprocess.run(["pkill", "-f", "ffmpeg"])
    notify("Recording Stopped", "Saved to Videos")


def prompt_stop_recording(ongoing_info: Tuple[str, str, str]):
    rec_type, audio, outfile = ongoing_info
    msg = "<b>Active recording</b>"
    msg += f" | Type: {rec_type}"
    msg += f" | Audio: {audio}"
    msg += f" | File: {outfile}"
    print(f"\0message\x1f{msg}")
    print(f"{STOP_RECORDING}{chr(0)}info\x1f{STOP_RECORDING}")


def show_recording_options() -> None:
    print("\0message\x1fStart Recording")
    for option in RecordingOption:
        print(f"{option.value}{chr(0)}info\x1f{option.value}")


if __name__ == "__main__":
    retv = int(os.environ.get("ROFI_RETV", 0))

    if retv == 0:
        # Initial Call, show options!
        if current_recording := get_recording_info():
            prompt_stop_recording(current_recording)
        else:
            show_recording_options()

    elif retv == 1:
        selection = os.environ.get("ROFI_INFO")
        if selection == STOP_RECORDING:
            stop_recording()
        elif selection == RecordingOption.SCREENSHOT_REGION.value:
            take_region_screenshot()
        elif selection == RecordingOption.SCREEN_AND_MIC.value:
            start_screen_mic()
        elif selection == RecordingOption.SCREEN_AND_SYS.value:
            start_screen_system_audio()
        elif selection == RecordingOption.SCREEN_ONLY.value:
            start_screen_silent()
        elif selection == RecordingOption.SCREENSHOT.value:
            take_screenshot()
        elif selection == RecordingOption.AUDIO_ONLY.value:
            start_audio_only()

    exit(0)
