#!/usr/bin/env python3

import subprocess
import os

performance_icon = "󱓞"
balanced_icon = "󰓅"
quiet_icon = "󰁻"

yes_icon = ""
no_icon = ""

config_dir = os.environ.get("XDG_CONFIG_HOME", "") + "/rofi"


def get_current_profile() -> str:
    result = subprocess.run(
        [
            "asusctl",
            "profile",
            "-p",
        ],
        capture_output=True,
        text=True,
    )
    return result.stdout.splitlines()[1].split()[-1]


def performance_profile_menu() -> None:
    opts = [
        ["Performance", performance_icon],
        ["Balanced", balanced_icon],
        ["Quiet", quiet_icon],
    ]

    current_profile = get_current_profile()
    print("\0prompt\x1fProfile")
    print(f"\0message\x1fCurrent Profile: {current_profile}")

    for mode, icon in opts:
        print(f"{icon} {mode}{chr(0)}info\x1f{mode.lower()}")


def set_performance_profile(profile: str) -> None:
    subprocess.run(
        ["asusctl", "profile", "-P", profile],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )

    subprocess.run(
        [
            "notify-send",
            "⚡ Performance Mode",
            f"Set to: {profile.capitalize()}",
            "--expire-time=2000",
            "-u",
            "normal",
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )


if __name__ == "__main__":
    selection = os.environ.get("ROFI_INFO")

    if selection:
        set_performance_profile(selection)
    else:
        performance_profile_menu()
